### ISSUE TITLE
@Controller annotation and route mapping issues

### ISSUE THREAD

**Issue by ghost** [dilsonjlrjr/slim3-annotation#4]
First of all it's really the cuttest annotations library for slim I've ever seen. It keeps the micro philosophy and does not disturb neither middlewares nor php-di, just if you add some caching it will be perfect. 

However I met two issues.
1)In my case It did not work without @Controller annotation within controller (noting mentioned in your manual) but as far as I can see required in CollectorRoute.php:

`preg_match('/@[ˆcC]ontroller/', $reflactionClass->getDocComment(), $arrayMatch);`

2)I had to modify a bit the code of Slim3Annotation.php:
line 23 from:

`$route = $application->map([$routeModel->getVerb()], $routeModel->getRoute(), $routeModel->getClassName() . ':' . $routeModel->getMethodName());` 

into:

`$route = $application->map([$routeModel->getVerb()], $routeModel->getRoute(), [$routeModel->getClassName(),$routeModel->getMethodName()]);`

Except for this, I'm truly delighted. Thank you for your effort.

**Comment by dilsonjlrjr** [comment]
Show @tjgumis.

I already have the cached version ready.
You just have to perform some tests and submit.

I'm working on an improved Slim skeleton.
It's going to be a show.
